---
title: "R notes"
output: 
  html_document:
    includes:
      in_header: "favicon.html"
    theme: paper
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 2
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Reading in data using "base R"

Base R refers to all of the operations and functions that come built in to your R session without loading any *libraries*. Let's read in some data. Suppose you've made your measurements of lots of sounds and you've saved them in Excel (or some other spreadsheet program). It's really good practice to save the data as a ".csv" file or *comma-separated values*. This is a format that is easily readable by R. (You can read in .xls files as well but let's keep it software neutral for the moment). 

Your R Studio session should be divided into different windows. Locate the "Script" window. If you don't see it, go to the "plus" icon at the top and select "New script". This should open a window. It is here where you will put all of your commands.

You can input your commands directly at the command prompt ">" but it's good practice to see what you've done. If you save it in a script then it's always there and theoretically always reproducible. 

First let's try out some fun stuff:

2+2 #If you put a hashtag in front of your script, it "comments" it out (i.e., it won't operate over the comment)

3*2 #multiply
2^9 #exponents

(8+9)* 5 #operations

#The general structure of an R function is:
# function(arg1, arg2, ...)

#There are many built-in mathematical functions in R

sqrt(81) 

# You can assign variables to the output of a function

x <- (8+9) * sqrt(81)
x

# The command ls() will list all of the objects in your environment

ls()

# Let's read in some data. But first let's see what your working directory is.

getwd()

#make sure the data you want to read in is in the working directory.

tam <- read.csv(tam, header=TRUE)

#this should put the object "tam" in your environment

head(tam)
tail(tam)

#Introducing Tidyverse package --> a modern way of doing R, meant to make everything tidier than Base R.

install.packages('tidyverse')
library(tidyverse)

tam <- as_tibble(tam)


First you need some data. I have uploaded a .csv file [here](tam.csv)

#Try out some fun stuff

2+2 #If you put a hashtag in front of your script, it "comments" it out (i.e., it won't operate over the comment)

3*2 #multiply
2^9 #exponents

(8+9)* 5 #operations

#The general structure of an R function is:
# function(arg1, arg2, ...)

#There are many built-in mathematical functions in R

sqrt(81) 

# You can assign variables to the output of a function

x <- (8+9) * sqrt(81)
x

# The command ls() will list all of the objects in your environment

ls()

# Let's read in some data. But first let's see what your working directory is.

getwd()

#make sure the data you want to read in is in the working directory.

tam <- read.csv(tam, header=TRUE)

#this should put the object "tam" in your environment

head(tam)
tail(tam)

#Introducing Tidyverse package --> a modern way of doing R, meant to make everything tidier than Base R.

install.packages('tidyverse')
library(tidyverse)

tam <- as_tibble(tam)

